### ISSUE TITLE
Can I view the DDP with parameter: "with_hessians=False" as iLQR algorithm?

### ISSUE THREAD

**Issue by CodingCatMountain** [imgeorgiev/ddp#1]
Hi, @imgeorgiev . Thanks for sharing this repo. And the blog is very wonderful for the greenhand like me to learn DDP algorithm. May I ask a question about DDP and iLQR? I wander about if I set the parameter "with_hessians=False", whether the DDP algorithm can be viewed as iterative LQR algorithm or not? I am looking forward to your reply.

**Comment by imgeorgiev** [comment]
Yes, DDP without the hessians is iLQR, which works very well and is not nearly as computationally intensive.

**Comment by CodingCatMountain** [comment]
Thanks! @imgeorgiev May I ask, Do you have any plan to implement guided policy search algorithm which utilizing DDP/iLQR as trajectory generator for policy leanring? Actually, the motivation for me to learn DDP/iLQR is that I want to learn this effective and elegent RL algorithm. :)

**Comment by imgeorgiev** [comment]
That would be a cool project but it is definitely out of the scope of this repo. What I have implemented here is for easy of understanding rather than efficiency. For a real implementation you probably want to use some library for automatic differentiation (e.g. pytorch)
